import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./main.css";
import { Toaster, toast } from "sonner";
import SessionWrapper from "@/components/sessionWrapper";
import { HeaderContactData } from "./_components/HeaderContactData";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body
          className={`${montserrat.variable} bg-surface text-surface  antialiased`}
        >
          <Toaster richColors />
          <HeaderContactData/>
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}
